var listBat = {

	"monument": [
		{"nom":"La Maison Folie",
		 "adresse":"Rue des Arbalestriers, 8",
		 "commune":"Mons",
		 "Telephone":"+32 65 39 59 12",
		 "Mail":"maisonfolie@lemanege-mons.be",
		 "img_1":["img/15213124199_8907cf9d3a_o.jpg","img/15213201559_b2e7086112_o.jpg", "img/15213216999_ff1e0ceefa_o.jpg"],
		 "img":"nav_1.png",
		 "lat":"50.455689",
		 "long":"3.959263",
		 "architecte":"Atelier d’Architecture Matador ",
		 "info_architecte":"(Mons-Bruxelles, B.)",
		 "chapeau":"La Maison Folie de Mons, à l’instar du Palais de Tokyo, de l’Espace Lu à Nantes ou encore de la Condition Publique à Roubaix, n’a pas le souci de paraître mais seulement celui d’être au plus près de ceux qui l’habitent.",
		 "paragraphe":"<p>Invité à redéfinir simplement les zones d’accueil et d’accès de la salle de théâtre existante, le bureau d’architecture Matador est parvenu à réaffecter l’ensemble du domaine exploitable.</p><p>Si la salle de théâtre est restée dans son état initial, Matador, pratiquant une architecture de friche, revendique pleinement l’originalité des concepts d’ «espace des possibles» et de la «Margin’halle» – ces deux lieux proposant aux associations une série d’espaces modulables de qualité regroupés autour de la cour centrale.</p>",
		 "Maître_douvrage":"Ville de Mons, cofinancée par le Ministère de la Communauté française Wallonie-Bruxelles, Service des Infrastructures culturelles, et l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":"icook.png"
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":"met.png"
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":"jean.png"
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":"cing.png"
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":"table.png"
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":"madelaine.png"
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":"gribaumonts.png"
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":"imperatif.png"
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":"mercure.png"
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":"utopia.png"
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":"beurre.png"
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":"emilie.png"
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":"faitout.png"
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":"bercha.png"
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":"gourmands.png"
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":"quick.png"
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":"pizza.png"
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":"logo_mcdo.png"
		}
		
	]


		},
		{"nom":"Le Manège.Mons",
		 "adresse":"Rue des Soeurs Noires 4/A",
		 "commune":"Mons",
		 "Telephone":"065 39 98 00",
		 "Mail":"tickets@lemanege-mons.be",
		 "img_1":["img/manege_1.jpg", "img/manege_2.jpg","img/manege_3.jpg"],
		 "img":"nav_2.png",
		 "Site web":"www.lemanege.com",
		 "lat":"50.450324",
		 "long":"3.951553",
		 "architecte":"atelier d’architecture Pierre Hebbelinck",
		 "info_architecte":"(Liège, B.)",
		 "chapeau":"Le manège.mons regroupe plusieurs structures artistiques à dimension transfrontalière. Implanté dans un îlot en complète restructuration, son théâtre devait prendre place dans un ancien manège du début du 20ème siècle de taille modeste.",
		 "paragraphe":"<p>Cette contrainte spatiale, l’Atelier d’Architecture Pierre Hebbelinck va la détourner en concevant une salle libre de près de 600 places assises insérée comme un cur- seur dans l’ancien bâtiment. La forte présence de l’intervention architecturale, une étonnante structure de verre et de béton qui concentre pour reprendre l’architecte «80 % de l’enveloppe budgétaire, admettant pour le reste des interventions un état de pauvreté extrêmement important», confère au lieu de création une lisibilité immédiate.</p>",
		 "Maître_douvrage":"Ministère de la Communauté française Wallonie-Bruxelles, Service des Infrastructures culturelles, cofinancé par l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"Le dépôt des oeuvres d'art",
		 "adresse":"Rue des Arquebusiers 14",
		 "commune":"Mons",
		 "Telephone":"",
		 "Mail":"",
		 "img_1":["img/depot_1.jpg", "img/depot_2.jpg", "img/depot_3.jpg"],
		 "img":"nav_3.png",
		 "Site web":"",
		 "lat":"50.449285",
		 "long":"3.953790",
		 "architecte":"sélection à venir",
		 "info_architecte":"",
		 "chapeau":"Arsonic consiste en l’aménagement, sur le site de l’ancienne caserne des pompiers, d’un centre de production, de promotion et de concerts pour les musiques acoustiques et amplifiées contem- poraines, dites émergentes.",
		 "paragraphe":"<p>Porté par l’ensemble Musiques Nouvelles et le Centre des écritures contemporaines Numériques (CECN), ce projet infrastructurel se positionne en pôle d’excellence européen, offrant à la création (inter)nationale les conditions nécessaires à la réalisation, sur site, de productions, formations et programmes pédagogiques. Arsonic, de par son emplacement parti- culièrement visible à l’une des portes d’entrée de la ville, constituera aussi un signal fort pour 2015.</p>",
		 "Maître_douvrage":"Ministère de la Communauté française Wallonie-Bruxelles, Service des Infrastructures culturelles, cofinancé par l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"Les Abattoirs",
		 "adresse":"Rue de la Trouille, 17",
		 "commune":"Mons",
		 "Telephone":"+32 65 40 53 12",
		 "Mail":"polemusueal@ville.mons.be",
		 "img_1":["img/abattoir_1.jpg", "img/abattoir_2.jpg", "img/abattoir_3.jpg"],
		 "img":"nav_4.png",
		 "Site web":"www.abattoirs.mons.be",
		 "lat":"50.449059",
		 "long":"3.951980",
		 "architecte":"atelier d’architecture Matador (Mons-Bruxelles, B.), Filip roland archiscénographe",
		 "info_architecte":"(Bruxelles, B.)",
		 "chapeau":"Constituant un intéressant témoignage de l’ar- chitecture civile du 19ème siècle, les anciens Abattoirs sont organisés autour de la Grande Halle, destinée à des manifestations et des expo- sitions temporaires, de l’Etable, siège du World Crafts Council pour la Belgique francophone et du Frigo, réunissant une cafétéria et un espace polyvalent dédié au son et à l’image.",
		 "paragraphe":"<p>La réno- vation intérieure menée par Matador et l’archi- scénographe Filip Roland confère aux volumes premiers une grande lisibilité et une spatialité mise en évidence par la grande pureté de l’intervention architecturale.</p>",
		 "Maître_douvrage":"Ville de Mons, cofinancés par le Ministère de la Région wallonne et l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"Arsonic",
		 "adresse":"Rue de Nimy, 138",
		 "commune":"Mons",
		 "Telephone":"+32 65 39 59 39",
		 "Mail":"",
		 "img_1":["img/arsonic_1.jpg", "img/arsonic_2.jpg", ""],
		 "img":"nav_5.png",
		 "Site web":"http://www.mons2015.eu/fr/arsonic-inauguration",
		 "lat":"50.459442",
		 "long":"3.956172",
		 "architecte":"sélection à venir",
		 "info_architecte":"",
		 "chapeau":"Arsonic consiste en l’aménagement, sur le site de l’ancienne caserne des pompiers, d’un centre de production, de promotion et de concerts pour les musiques acoustiques et amplifiées contem- poraines, dites émergentes.",
		 "paragraphe":"<p>Porté par l’ensemble Musiques Nouvelles et le Centre des écritures contemporaines Numériques (CECN), ce projet infrastructurel se positionne en pôle d’excellence européen, offrant à la création (inter)nationale les conditions nécessaires à la réalisation, sur site, de productions, formations et programmes pédagogiques. Arsonic, de par son emplacement parti- culièrement visible à l’une des portes d’entrée de la ville, constituera aussi un signal fort pour 2015.</p>",
		 "Maître_douvrage":"Ministère de la Communauté française Wallonie-Bruxelles, Service des Infrastructures culturelles, cofinancé par l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"Le carré des Arts",
		 "adresse":"Rue des Soeurs Noires, 4/B",
		 "commune":"Mons",
		 "Telephone":"",
		 "Mail":"esapv.mons@esapv.be",
		 "img_1":["img/carre_1.jpg", "img/carre_2.jpg", "img/carre_3.jpg"],
		 "img":"nav_6.png",
		 "Site web":"http://www.esapv.be/",
		 "lat":"50.449974",
		 "long":"3.950840",
		 "architecte":"agWa (Bruxelles, B.) et ney & Partners",
		 "info_architecte":"(Bruxelles-Luxembourg)",
		 "chapeau":"La cour centrale de ce vaste édifice accueille régulièrement des manifestations culturelles. ",
		 "paragraphe":"<p>Pour optimi- ser au mieux l’usage de l’espace central à ciel ouvert, sans avoir recours à la location ponctuelle de chapiteaux, le Ministère de la Communauté française a lancé une étude de faisabilité pour sa couver- ture, remportée par l’association momentanée entre le jeune atelier d’architecture AGWA et le bureau d’ingénierie Ney & Partners.</p>",
		 "Maître_douvrage":"Ministère de la Communauté française Wallonie-Bruxelles, Service des infrastructures culturelles",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"Le BAM",
		 "adresse":"Rue Neuve, 8",
		 "commune":"Mons",
		 "Telephone":"+32 65 40 53 30",
		 "Mail":"polemusueal@ville.mons.be",
		 "img_1":["img/bam_1.jpg", "img/bam_2.jpg", "img/bam_4.jpg"],
		 "img":"nav_7.png",
		 "Site web":"http://www.bam.mons.be/",
		 "lat":"50.455548",
		 "long":"3.952406",
		 "architecte":"christian Menu architecte",
		 "info_architecte":"(Paris, F.)",
		 "chapeau":"La rénovation de l’ancien Musée des Beaux-Arts allie fonctionnalité et transparence.",
		 "paragraphe":"<p>L’architecte parisien a imaginé une véritable fenêtre ouverte sur le monde de l’art et de la création. Pour ce faire, il a opté pour une légère structure métallique. Le réaménagement des salles permet au nouveau musée d’accueillir des œuvres prestigieuses tout en respectant les normes de sécurité européennes. L’idée phare est d’ouvrir, par la transparence, le BAM à la rue.</p>",
		 "Maître_douvrage":"L’architecte parisien a imaginé une véritable fenêtre ouverte sur le monde de l’art et de la création. Pour ce faire, il a opté pour une légère structure métallique. Le réaménagement des salles permet au nouveau musée d’accueillir des œuvres prestigieuses tout en respectant les normes de sécurité européennes. L’idée phare est d’ouvrir, par la transparence, le BAM à la rue.",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"Le corps de ville",
		 "adresse":"Rue des Trois Boudins 11",
		 "commune":"Mons",
		 "Telephone":"+32 65 395912",
		 "Mail":"maisonfolie@lemanege-mons.be",
		 "img_1":["img/corps_1.jpg", "img/corps_2.jpg", "img/corps_3.jpg"],
		 "img":"nav_8.png",
		 "Site web":"",
		 "lat":"50.459217",
		 "long":"3.956827",
		 "architecte":"atelier d’architecture Matador, robbrecht & Daem",
		 "info_architecte":"(Mons-Bruxelles, B.), (gand, B.)",
		 "chapeau":"La spécificité de la démarche initiée par la Ville de Mons tient dans les critères de qualités urbanistique et architecturale qu’elle institue pour la sélection des projets, contraignant les promoteurs immobiliers candi- dats à s’associer avec des architectes autour d’une proposition commune.",
		 "paragraphe":"<p>Le projet «Corps de Ville», désigné lauréat par le jury, rencontre les options du plan-masse initial et en formule de nouvelles pour nourrir le dialogue entre les utilisateurs de ce site névralgique pour la candida- ture de Mons au titre de Capitale européenne de la Culture en 2015.</p>",
		 "Maître_douvrage":"Himmos NV projectontwikkeling (Antwerpen, B.)",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"La Gare",
		 "adresse":"Boulevard Charles Quint, 33",
		 "commune":"Mons",
		 "Telephone":"+32 2 528 28 28",
		 "Mail":"",
		 "img_1":["img/gare_1.jpg", "img/gare_2.jpg", "img/gare_3.jpg"],
		 "img":"nav_9.png",
		 "Site web":"www.belgianrail.be",
		 "lat":"50.456727",
		 "long":"3.944703",
		 "architecte":"santiago calatrava",
		 "info_architecte":"(valencia, esp.)",
		 "chapeau":"Le projet d’une nouvelle Gare visait notamment à faciliter l’accès aux quais depuis la place et les parkings, d’optimiser l’accessibilité à la gare et son intermodalité et de liaisonner le cœur historique de Mons et le développe- ment d’une nouvelle ville sur le site des Grands-Prés.",
		 "paragraphe":"<p>Cette gare-passerelle devient l’élément majeur autour duquel s’organisent symétriquement les quais et la place. Elle jouera pleinement son rôle de trait d’union entre la ville de patrimoine et ses nouveaux quartiers dédiés au commerce, à l’habitat et aux nouvelles technologies.</p>",
		 "Maître_douvrage":"Ville de Mons, SNCB, Infrabel, EuroLiège TGV",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
		{"nom":"La Fondation Mons 2015",
		 "adresse":"Rue de Nimy, 106",
		 "commune":"Mons",
		 "Telephone":"+32 65 36 20 15",
		 "Mail":"",
		 "img_1":["img/fondation_1.jpg", "img/fondation_2.jpg", "img/fondation_3.jpg"],
		 "img":"nav_10.png",
		 "Site web":"www.mons2015.eu",
		 "lat":"50.458492",
		 "long":"3.955646",
		 "architecte":"sélection en cours",
		 "info_architecte":"",
		 "chapeau":"Le bâtiment de l’ancienne Académie des Beaux-Arts est appelé à devenir le centre névralgique de la production et de la promotion de la culture de la Ville et à jouer un rôle emblématique d’accueil du public et des artistes et d’information à la presse dans la perspective de la candidature de Mons au titre de Capitale européenne de la Culture en 2015.",
		 "paragraphe":"Inscrit dans la mémoire des habitants depuis des générations, l’édifice devra être tout autant l’incarnation de notre modernité en architecture.",
		 "Maître_douvrage":"Ministère de la Communauté française Wallonie-Bruxelles, Service des Infrastructures culturelles, cofinancée par l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":"",
		 "restaurant" : [
		{"nom":"iCook!",
		 "adresse":"Rue des Fripiers, 2",
		 "commune":"Mons",
		 "distance":"100 m",
		 "logo":""
		},
		{"nom":"L'arts des mets",
		 "adresse":"Rue des Clercs, 9",
		 "commune":"Mons",
		 "distance":"200 m",
		 "logo":""
		},
		{"nom":"Le bistro de Jean-Phi",
		 "adresse":"Rue des Fripiers, 22b",
		 "commune":"Mons",
		 "distance":"300 m",
		 "logo":""
		},
		{"nom":"La 5e saison",
		 "adresse":"Rue de la Coupe, 25",
		 "commune":"Mons",
		 "distance":"400 m",
		 "logo":""
		},
		{"nom":"La Table des Matières",
		 "adresse":"Rue du Grand Trou Oudart, 16",
		 "commune":"Mons",
		 "distance":"500 m",
		 "logo":""
		},
		{"nom":"La Madeleine",
		 "adresse":"Rue de la Halle, 42",
		 "commune":"Mons",
		 "distance":"600 m",
		 "logo":""
		},
		{"nom":"Les Gribaumonts",
		 "adresse":"Rue d’Havé, 95",
		 "commune":"Mons",
		 "distance":"700 m",
		 "logo":""
		},
		{"nom":"L'Impératif",
		 "adresse":"Rue Grande, 208",
		 "commune":"Maisières",
		 "distance":"800 m",
		 "logo":""
		},
		{"nom":"Mercure",
		 "adresse":"Rue des Fusillés, 12",
		 "commune":"Nimy",
		 "distance":"900 m",
		 "logo":""
		},
		{"nom":"Utopia",
		 "adresse":"Chaussée Brunehault, 392b ",
		 "commune":"Masnuy-Saint-Jean",
		 "distance":"1000 m",
		 "logo":""
		},
		{"nom":"L’Assiette au Beurre",
		 "adresse":"Rue de l’industrie, 278",
		 "commune":"FRAMERIES",
		 "distance":"1100 m",
		 "logo":""
		},
		{"nom":"d’Eugènie à Emilie",
		 "adresse":"Place de la résistance, 1",
		 "commune":"Baudour",
		 "distance":"1200 m",
		 "logo":""
		},
		{"nom":"Le Faitout",
		 "adresse":"Avenue Louis Goblet, 161",
		 "commune":"Baudour",
		 "distance":"1300 m",
		 "logo":""
		},
		{"nom":"Le Bercha",
		 "adresse":"Route de Mons, 763",
		 "commune":"Bray",
		 "distance":"1400 m",
		 "logo":""
		},
		{"nom":"Les Gourmands ",
		 "adresse":"Rue de Sars, 15",
		 "commune":"Blaregnies",
		 "distance":"1500 m",
		 "logo":""
		},
		{"nom":"Quick",
		 "adresse":"Avenue Wilson, 510",
		 "commune":"Mons",
		 "distance":"1600 m",
		 "logo":""
		},
		{"nom":"Pizza Hut",
		 "adresse":"Place Léopold, 7",
		 "commune":"Mons",
		 "distance":"1700 m",
		 "logo":""
		},
		{"nom":"MacDonalds",
		 "adresse":"Grand Place, 39",
		 "commune":"Mons",
		 "distance":"1800 m",
		 "logo":""
		}
		
	]
		},
	],
	
	
};