var listBat = {

	"monument": [
		{"nom":"La Maison Folie",
		 "adresse":"Rue des Arbalestriers, 8",
		 "Commune":"Mons",
		 "Telephone":"+32 65 39 59 12",
		 "Mail":"maisonfolie@lemanege-mons.be",
		 "Site web":"www.maisonfoliemons.be",
		 "lat":"50.455689",
		 "long":"3.959263",
		 "architecte":"Atelier d’Architecture Matador ",
		 "info_architecte":"(Mons-Bruxelles, B.)",
		 "chapeau":"La Maison Folie de Mons, à l’instar du Palais de Tokyo, de l’Espace Lu à Nantes ou encore de la Condition Publique à Roubaix, n’a pas le souci de paraître mais seulement celui d’être au plus près de ceux qui l’habitent.",
		 "paragraphe":"<p>Invité à redéfinir simplement les zones d’accueil et d’accès de la salle de théâtre existante, le bureau d’architecture Matador est parvenu à réaffecter l’ensemble du domaine exploitable.</p><p>Si la salle de théâtre est restée dans son état initial, Matador, pratiquant une architecture de friche, revendique pleinement l’originalité des concepts d’ «espace des possibles» et de la «Margin’halle» – ces deux lieux proposant aux associations une série d’espaces modulables de qualité regroupés autour de la cour centrale.</p>",
		 "Maître_douvrage":"Ville de Mons, cofinancée par le Ministère de la Communauté française Wallonie-Bruxelles, Service des Infrastructures culturelles, et l’Union Européenne – Fonds FEDER",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":""


		},
		{"nom":"Le Manège.Mons",
		 "adresse":"Rue des Soeurs Noires 4/A",
		 "Commune":"Mons",
		 "Telephone":"065 39 98 00",
		 "Mail":"tickets@lemanege-mons.be",
		 "Site web":"www.lemanege.com",
		 "lat":"50.450324",
		 "long":"3.951553",
		 "architecte":"",
		 "info_architecte":"",
		 "chapeau":"",
		 "paragraphe":"",
		 "Maître_douvrage":"",
		 "pt_img":"",
		 "pt_titre":"",
		 "pt_paragraphe":""
		},
		{"nom":"Le dépôt des oeuvres d'art",
		 "adresse":"Rue des Arquebusiers 14",
		 "Commune":"Mons",
		 "Telephone":"",
		 "Mail":"",
		 "Site web":"",
		 "lat":"50.449285",
		 "long":"3.953790"
		},
		{"nom":"Les Abatoires",
		 "adresse":"Rue de la Trouille, 17",
		 "Commune":"Mons",
		 "Telephone":"+32 65 40 53 12",
		 "Mail":"polemusueal@ville.mons.be",
		 "Site web":"www.abattoirs.mons.be",
		 "lat":"50.449059",
		 "long":"3.951980"
		},
		{"nom":"Arsonic",
		 "adresse":"Rue de Nimy, 138",
		 "Commune":"Mons",
		 "Telephone":"+32 65 39 59 39",
		 "Mail":"",
		 "Site web":"http://www.mons2015.eu/fr/arsonic-inauguration",
		 "lat":"50.459442",
		 "long":"3.956172"
		},
		{"nom":"Le carré des Arts",
		 "adresse":"Rue des Soeurs Noires, 4/B",
		 "Commune":"Mons",
		 "Telephone":"",
		 "Mail":"esapv.mons@esapv.be",
		 "Site web":"http://www.esapv.be/",
		 "lat":"50.449974",
		 "long":"3.950840"
		},
		{"nom":"Le BAM",
		 "adresse":"Rue Neuve, 8",
		 "Commune":"Mons",
		 "Telephone":"+32 65 40 53 30",
		 "Mail":"polemusueal@ville.mons.be",
		 "Site web":"http://www.bam.mons.be/",
		 "lat":"50.455548",
		 "long":"3.952406"
		},
		{"nom":"Le corps de ville",
		 "adresse":"Rue des Trois Boudins 11",
		 "Commune":"Mons",
		 "Telephone":"+32 65 395912",
		 "Mail":"maisonfolie@lemanege-mons.be",
		 "Site web":"",
		 "lat":"50.459217",
		 "long":"3.956827"
		},
		{"nom":"La Gare",
		 "adresse":"Boulevard Charles Quint, 33",
		 "Commune":"Mons",
		 "Telephone":"+32 2 528 28 28",
		 "Mail":"",
		 "Site web":"www.belgianrail.be",
		 "lat":"50.456727",
		 "long":"3.944703"
		},
		{"nom":"La Fondation Mons 2015",
		 "adresse":"Rue de Nimy, 106",
		 "Commune":"Mons",
		 "Telephone":"+32 65 36 20 15",
		 "Mail":"",
		 "Site web":"www.mons2015.eu",
		 "lat":"50.458492",
		 "long":"3.955646"
		},
	]
};